### ISSUE TITLE
Doesn't work in projects using URP

### ISSUE THREAD

**Issue by SamIngram** [gilzoide/unity-texture-apply-async#3]
Empty project in Unity 6000 with only this, render texture comes out grey in sample.

Can confirm the same process for Unity 2022 works as intended.

Any assistance/suggestions would be greatly appreciated!

**Comment by gilzoide** [comment]
Hey @SamIngram, thanks for the report.
I don't have Unity 6 here yet to test this out, haven't ever installed/opened it to be honest.
Are there any error messages there that could give any clue of what's going on?

**Comment by SamIngram** [comment]
@gilzoide Thanks for the quick reply! Was wholly unexpected!

No error messages at all. It creates a partially transparent, completely flatly coloured image (I think it's white). I tried a script to set all the pixels to red, and the result is exactly the same.

There's no desperate rush on my end for a fix, I'll just roll my project into 2022 and work with that.

Just thought you'd want to know!

**Comment by SamIngram** [comment]
Okay, curiously if I manually open the texture after it's been created in play mode, and change any of the settings, then the random colours appear. Every time I change a setting, it updates (presumably Unity calling Texture.Apply). Not sure if that helps at all.

**Comment by gilzoide** [comment]
> No error messages at all

Oh, ok, so the plugin is likely being loaded correctly.

> Just thought you'd want to know!

Thanks, I do want to know this kind of stuff =]

> Okay, curiously if I manually open the texture after it's been created in play mode

What do you mean by "open the texture"? I mean, Unity's `Texture.Apply` is about applying pixel data from general RAM memory to the GPU memory, it should only exist in memory and exiting play mode isn't supposed to save those changes anywhere.

I'll install Unity 6 here and test the samples provided by the package.

**Comment by gilzoide** [comment]
The "Plasma Color Job" sample is working fine here in the editor 🤔 Unity 6000.0.22f1 on a macOS, in this case.

<img width="785" alt="Screenshot 2024-10-07 at 06 38 27" src="https://github.com/user-attachments/assets/26f0b514-6cd4-4077-a70f-549b72ee546d">

**Comment by SamIngram** [comment]
@gilzoide 6000.0.22f1 doesn't work for me on Mac using Apple Silicon. Neither sample is working for me in any version of Unity 6. Did you adjust any settings before running the samples?

**Comment by SamIngram** [comment]
Also doesn't with 6000.0.22f1 on Mac Intel, for me. I'll keep testing.

**Comment by SamIngram** [comment]
@gilzoide It appears that it's not to do with Unity 6, but that it doesn't work with the Universal Render Pipeline. In my tests URP doesn't work in either 2022 or 6, but the Built-In works in both. 

All tests were done on clean installs of both Unity Hub and Unity Version 6 or 2022. The projects were new and I installed only your plugin (using package manager). Installed on a MacBook with Apple Silicon.

**Comment by SamIngram** [comment]
By the way, if I change your samples code to call Texture.Apply the normal way in URP, the texture updates as expected.

**Comment by gilzoide** [comment]
Oooh, ok, so it's not about Unity 6, but rather Builtin RP vs SRP. Thanks for finding this out, I'll rename the issue accordingly.

Guess the "CustomTextureUpdateV2" graphics command doesn't work on SRP, or at least not when using CommandBuffers on Cameras. I've never used CommandBuffers on SRP, would need to study how it works and could we inject the textures to be applied in SRP automatically.

**Comment by gilzoide** [comment]
Hey @SamIngram, I found how to make this package run in SRP-enabled projects, it's just like in Builtin RP: you register a callback that gets called before the frame starts rendering and schedule your command buffer in the `ScriptableRenderContext`.
It's in branch [support-urp](https://github.com/gilzoide/unity-texture-apply-async/tree/support-urp) if you want to test the fix before we merge it and release the fix.

**Comment by gilzoide** [comment]
Hey @SamIngram, I released version 1.1.0 with the fix.
If the problem persists, feel free to reopen the issue.
Cheers \o/
